//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookShop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineBookShop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _124207249_marketing_des_médias_sociaux_concept_de_réseau_de_communication_icônes_aléatoires_balises_de {
            get {
                object obj = ResourceManager.GetObject("124207249-marketing-des-médias-sociaux-concept-de-réseau-de-communication-icônes-" +
                        "aléatoires-balises-de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1eec8d52cbdb60d1932df63b38a3f987 {
            get {
                object obj = ResourceManager.GetObject("1eec8d52cbdb60d1932df63b38a3f987", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _295db05185d1dc2fa04dbd7f2d75126c {
            get {
                object obj = ResourceManager.GetObject("295db05185d1dc2fa04dbd7f2d75126c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_104965579_I7QiErzc032ylXRaWt9XsmIcgzu3BaDJ {
            get {
                object obj = ResourceManager.GetObject("360_F_104965579_I7QiErzc032ylXRaWt9XsmIcgzu3BaDJ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_104965579_I7QiErzc032ylXRaWt9XsmIcgzu3BaDJ1 {
            get {
                object obj = ResourceManager.GetObject("360_F_104965579_I7QiErzc032ylXRaWt9XsmIcgzu3BaDJ1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_104965579_I7QiErzc032ylXRaWt9XsmIcgzu3BaDJ2 {
            get {
                object obj = ResourceManager.GetObject("360_F_104965579_I7QiErzc032ylXRaWt9XsmIcgzu3BaDJ2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_471645030_nlJLtBf88pxHCy9qFCMG6VhrtXkJ0Abq {
            get {
                object obj = ResourceManager.GetObject("360_F_471645030_nlJLtBf88pxHCy9qFCMG6VhrtXkJ0Abq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4202011emailgmaillogomailsocialsocialmedia_115677_115624 {
            get {
                object obj = ResourceManager.GetObject("4202011emailgmaillogomailsocialsocialmedia-115677_115624", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _510 {
            get {
                object obj = ResourceManager.GetObject("510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cute_woman_read_book_cartoon_illustration_97231_2220 {
            get {
                object obj = ResourceManager.GetObject("cute-woman-read-book-cartoon-illustration_97231-2220", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap facebook_logo_icon_147291 {
            get {
                object obj = ResourceManager.GetObject("facebook_logo_icon_147291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_library_concept_showing_people_interacting_with_digital_books_reading_books_online_e_book_concept_read_digital_books_device_use_for_reading_flat_illustrat {
            get {
                object obj = ResourceManager.GetObject("online-library-concept-showing-people-interacting-with-digital-books-reading-book" +
                        "s-online-e-book-concept-read-digital-books-device-use-for-reading-flat-illustrat" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_library_concept_showing_people_interacting_with_digital_books_reading_books_online_e_book_concept_read_digital_books_device_use_for_reading_flat_illustrat1 {
            get {
                object obj = ResourceManager.GetObject("online-library-concept-showing-people-interacting-with-digital-books-reading-book" +
                        "s-online-e-book-concept-read-digital-books-device-use-for-reading-flat-illustrat" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap student_girl_studying_with_laptop_young_woman_sitting_stack_books_getting_knowledge_online_illustration_e_learning_internet_course_school_concept_460582_51 {
            get {
                object obj = ResourceManager.GetObject("student-girl-studying-with-laptop-young-woman-sitting-stack-books-getting-knowled" +
                        "ge-online-illustration-e-learning-internet-course-school-concept_460582-51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Twitter_icon_icons_com_66803 {
            get {
                object obj = ResourceManager.GetObject("Twitter_icon-icons.com_66803", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whatsapp_37229 {
            get {
                object obj = ResourceManager.GetObject("Whatsapp_37229", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
